apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: message-dumper
  namespace: seldon
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: psilvaleo/message-dumper
