apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: flowi-preprocessing-8d5eada3-cee5-4002-b975-07c676a5e789
  namespace: default
spec:
  timeToLiveSeconds: 10
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: localhost:32000/flowi-preprocessing
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/sandbox_mllib.py"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    envVars:
      RUN_ID: "8d5eada3-cee5-4002-b975-07c676a5e789"
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    envVars:
      RUN_ID: "8d5eada3-cee5-4002-b975-07c676a5e789"
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
