apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dask
  namespace: flowi
spec:
  hosts:
  - "dask.flowi.cloud"
  gateways:
  - flowi-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: dask-scheduler
