---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: flowi
---
# Allows Airflow to grab config maps (airflow.cfg)
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-config
  namespace: flowi
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: flowi
roleRef:
  kind: Role
  name: airflow-get-config
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-get-config
  namespace: flowi
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
# Allows Airflow to read secrets from Kubernetes
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-secret-reader
  namespace: flowi
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-reader
  namespace: flowi
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Allows Airflow to delete pods when using the Kubernetes PodOperator
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-binding
  namespace: flowi
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: flowi
roleRef:
  kind: Role
  name: pod-create-delete
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-create-delete
  namespace: flowi
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
