apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  namespace: flowi
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: localhost:32000/airflow
        ports:
        - containerPort: 8080
