apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQUpMQnBzcHdCY0pOTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU1UQXlNVGN3TURVeU1UUmFGdzB6TVRBeU1UVXdNRFV5TVRSYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFMQjc2QS82QzFsZFUxTVZUSDNacTdaT3c5ekNkYkhaMDM1VnA5eW05MGduRXpzUUFheG4KZWVINDdZTklHeXNUR3ZKZkNjRTJLanVRcklLNUwvT1NabGxzWHA5bEdZam5mR0lrZ0Rubi9aWHRrTU0vZy81dQpNQjhOcks5WnBXb2N0UFFpTXNjSmJSdklBRXVVc0ZCczVXTFpCVlk1VnhPWTI1VVVtZi9XN2pvdVcyM21GTllYCnY0K1BZTkFlRjVhM1VBWSt5djdIVWpqT0M0V2ZKaWx2MnA2WS9BY1VVdHdRWGJqVFNDUTdTQVlTdDVQWStmMkEKdi80UWpGYjRncElxUVVOOG1zUWhib05TTEtCRWQ2QVVtSzR5dVFVbXRkYkkvcGppbHpxRmYrN21TMThkTnBTSwpVNHlBL0VaYVBpMTE1WnB5eXhVQ1dRUXB1YjNJUkJTQW5Xc0NBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGRmJqCnU0VnBPMDdYbnhiay9YZzFHbExRMDJBU01COEdBMVVkSXdRWU1CYUFGRmJqdTRWcE8wN1hueGJrL1hnMUdsTFEKMDJBU01Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUNNKzlVUGtZWnBkMUg4RQorak92c2o3UzF1SnRaaENMK05yQVBQVVFTOVppaHhKbWsvZzNiV3lyYlBULzhXK2NUdDczQ29GQ3J4NlYrQlNSCkJtVWgrcVNPM05jc1lIcWpJZ3FVbXVoTWUvdkZ3c0NIV25rbWVoMFZQUGxLRXRZcnVnd1c2T0tiTmJwS2xob0EKT3RkWnJNNjFFMWJqNjcwa005V0pnZEZQVWxWWkxGeDM5WTk0VUQ4bUp2RFE3Y3BpcGxJRlVEcGpZdGx3NmNHSApJWm5zWFZxMDlGK004dkdXVDJFdnRkWmxxbTg5S29WT2liZW1ONVE3aTRGaHFObnFHTjNPbUpUSWJnWHU2dlJKCnBCcjdiUENRWitrTGhDUDl6WUJ3Tzl6VGdzNk14Tkw5R1RQay95Z1dXSXBML0dlSXBEcFl6MWNzTE82M3VpWGcKdE1Qdi9jZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://kubernetes.default.svc
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    namespace: default
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: a1UxYlVxNEJUWDZsZ0IvUUZxL3A0WE1xSEUrYkZDTXVRWUVtcWNCRUFkWT0K
