version: '3'
services:
    flowi-nginx:
        image: nginx:latest
        container_name: flowi-nginx
        volumes:
          - ./nginx/:/etc/nginx/
        ports:
          - 80:80
        depends_on:
          - flowi-airflow

    flowi-front:
        image: flowi-front
        restart: always
        ports:
            - "3000:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ curl -f http://localhost:3000 || false ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flowi-airflow:
        image: flowi-airflow
        restart: always
#        depends_on:
#            - postgres
#            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
#            - EXECUTOR=Celery
#             - POSTGRES_USER=airflow
#             - POSTGRES_PASSWORD=airflow
#             - POSTGRES_DB=airflow
#             - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
            - /var/run/docker.sock:/var/run/docker.sock
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
            - "5000:5000"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

#    flower:
#        image: docker-airflow
#        restart: always
#        depends_on:
#            - redis
#        environment:
#            - EXECUTOR=Celery
#             - REDIS_PASSWORD=redispass
#        ports:
#            - "5555:5555"
#        command: flower
#
#    scheduler:
#        image: docker-airflow
#        restart: always
#        depends_on:
#            - webserver
#        volumes:
#            - ./dags:/usr/local/airflow/dags
#            # Uncomment to include custom plugins
#            # - ./plugins:/usr/local/airflow/plugins
#        environment:
#            - LOAD_EX=n
#            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
#            - EXECUTOR=Celery
#             - POSTGRES_USER=airflow
#             - POSTGRES_PASSWORD=airflow
#             - POSTGRES_DB=airflow
#            # - REDIS_PASSWORD=redispass
#        command: scheduler
#
#    worker:
#        image: docker-airflow
#        restart: always
#        depends_on:
#            - scheduler
#        volumes:
#            - ./dags:/usr/local/airflow/dags
#            # Uncomment to include custom plugins
#            # - ./plugins:/usr/local/airflow/plugins
#        environment:
#            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
#            - EXECUTOR=Celery
#             - POSTGRES_USER=airflow
#             - POSTGRES_PASSWORD=airflow
#             - POSTGRES_DB=airflow
#            # - REDIS_PASSWORD=redispass
#        command: worker
